root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
settings:
  react:
    version: detect
ignorePatterns:
  - node_modules/
  - src-tauri/
  - public/
  - dist/
rules:
  react/jsx-no-target-blank: 'off'
